name: GeoKintai
options:
  deploymentTarget:
    iOS: '17.0'
  bundleIdPrefix: com.geokintai
configs:
  Debug: debug
  Release: release
settings:
  PRODUCT_BUNDLE_IDENTIFIER: com.geokintai.GeoKintai
  DEVELOPMENT_TEAM: ""
  SWIFT_VERSION: 5.9
  INFOPLIST_FILE: GeoKintai/Resources/Info.plist
  CODE_SIGN_STYLE: Automatic
  CURRENT_PROJECT_VERSION: 1
  MARKETING_VERSION: 0.1.0
  ENABLE_USER_SCRIPT_SANDBOXING: YES
  CLANG_ANALYZER_NONNULL: YES
  CLANG_ANALYZER_NUMBER_OBJECT_CONVERSION: YES_AGGRESSIVE
  CLANG_ANALYZER_SECURITY_FLOATLOOPCOUNTER: YES
  CLANG_WARN_BLOCK_CAPTURE_AUTORELEASING: YES
  CLANG_WARN_BOOL_CONVERSION: YES
  CLANG_WARN_COMMA: YES
  CLANG_WARN_CONSTANT_CONVERSION: YES
  CLANG_WARN_DEPRECATED_OBJC_IMPLEMENTATIONS: YES
  CLANG_WARN_DIRECT_OBJC_ISA_USAGE: YES_ERROR
  CLANG_WARN_DOCUMENTATION_COMMENTS: YES
  CLANG_WARN_EMPTY_BODY: YES
  CLANG_WARN_ENUM_CONVERSION: YES
  CLANG_WARN_INFINITE_RECURSION: YES
  CLANG_WARN_INT_CONVERSION: YES
  CLANG_WARN_NON_LITERAL_NULL_CONVERSION: YES
  CLANG_WARN_OBJC_IMPLICIT_RETAIN_SELF: YES
  CLANG_WARN_OBJC_LITERAL_CONVERSION: YES
  CLANG_WARN_OBJC_ROOT_CLASS: YES_ERROR
  CLANG_WARN_QUOTED_INCLUDE_IN_FRAMEWORK_HEADER: YES
  CLANG_WARN_RANGE_LOOP_ANALYSIS: YES
  CLANG_WARN_STRICT_PROTOTYPES: YES
  CLANG_WARN_SUSPICIOUS_MOVE: YES
  CLANG_WARN_UNGUARDED_AVAILABILITY: YES_AGGRESSIVE
  CLANG_WARN_UNREACHABLE_CODE: YES
  CLANG_WARN__DUPLICATE_METHOD_MATCH: YES
  ENABLE_STRICT_OBJC_MSGSEND: YES
  GCC_WARN_64_TO_32_BIT_CONVERSION: YES
  GCC_WARN_ABOUT_RETURN_TYPE: YES_ERROR
  GCC_WARN_UNDECLARED_SELECTOR: YES
  GCC_WARN_UNINITIALIZED_AUTOS: YES_AGGRESSIVE
  GCC_WARN_UNUSED_FUNCTION: YES
  GCC_WARN_UNUSED_VARIABLE: YES
  SUPPORTS_MACCATALYST: NO
  SUPPORTS_MAC_DESIGNED_FOR_IPHONE_IPAD: NO
  TARGETED_DEVICE_FAMILY: 1
  SWIFT_STRICT_CONCURRENCY: complete
  SWIFT_TREAT_WARNINGS_AS_ERRORS: NO
  ASSETCATALOG_COMPILER_APPICON_NAME: ""

targets:
  GeoKintai:
    type: application
    platform: iOS
    sources:
      - path: GeoKintai
    settings:
      base:
        INFOPLIST_FILE: GeoKintai/Resources/Info.plist
        ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES: YES
    dependencies: []
  GeoKintaiTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: GeoKintaiTests
      - path: SimulatedLocations
        buildPhase: resources
    dependencies:
      - target: GeoKintai
    settings:
      base:
        INFOPLIST_FILE: GeoKintaiTests/Resources/Info.plist
        ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES: YES
