name: GeoKintai
options:
  deploymentTarget:
    iOS: "17.0"

targets:
  GeoKintaiCore:
    type: framework
    platform: iOS
    deploymentTarget: "17.0"
    sources:
      - path: Sources/geoKintai
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.komorikouki.GeoKintaiCore
        GENERATE_INFOPLIST_FILE: YES
        SKIP_INSTALL: YES
        ENABLE_APP_INTENTS_METADATA_GENERATION: NO

  GeoKintaiApp:
    type: application
    platform: iOS
    deploymentTarget: "17.0"
    sources:
      - path: App/GeoKintaiApp
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.komorikouki.GeoKintai
        INFOPLIST_FILE: App/GeoKintaiApp/Info.plist
        TARGETED_DEVICE_FAMILY: "1,2"
        ASSETCATALOG_COMPILER_APPICON_NAME: ""
        CODE_SIGN_STYLE: Automatic
        DEVELOPMENT_TEAM: ""
        ENABLE_APP_INTENTS_METADATA_GENERATION: NO
    dependencies:
      - target: GeoKintaiCore

  GeoKintaiAppTests:
    type: bundle.unit-test
    platform: iOS
    deploymentTarget: "17.0"
    sources:
      - path: App/GeoKintaiAppTests
    settings:
      base:
        GENERATE_INFOPLIST_FILE: YES
        PRODUCT_BUNDLE_IDENTIFIER: com.komorikouki.GeoKintaiTests
        ENABLE_APP_INTENTS_METADATA_GENERATION: NO
    dependencies:
      - target: GeoKintaiApp
      - target: GeoKintaiCore

schemes:
  GeoKintaiApp:
    build:
      targets:
        GeoKintaiCore: all
        GeoKintaiApp: all
        GeoKintaiAppTests: [test]
    test:
      targets:
        - GeoKintaiAppTests
